In [6]:
import pyterrier as pt
pt.init(version='snapshot')
import pyt_splade

dataset = pt.get_dataset('irds:msmarco-passage')
splade = pyt_splade.SpladeFactory()

indexer = pt.IterDictIndexer('./msmarco_psg', pretokenised=True)

indxer_pipe = splade.indexing() >> indexer
indxer_pipe.index(dataset.get_corpus_iter(

jack_splade = PyTerrierSPLADE(
    model_name = "lsr42/splade",
    verbose = True,
    index_location = "./indices/vaswani_sparse_test",
    index_name = "vaswani_sparse_test"
)

exp = pt.Experiment(
    [craig_splade_pipe, jack_splade],
    dataset.get_topics(),
    dataset.get_qrels(),
    eval_metrics=[nDCG@10, "mrt"],
    names = ["Craig SPLADE", "Jack SPLADE"]
)

print(exp)

vaswani documents:   0%|          | 0/11429 [02:20<?, ?it/s]

           name   nDCG@10        mrt
0  Craig SPLADE  0.002505  19.280256
1   Jack SPLADE  0.471074  13.010743

In [3]:
indexer = pt.IterDictIndexer('./indices/craig_vaswani', pretokenised=True)

indxr_pipe = craig_splade.indexing() >> indexer
index_ref = indxr_pipe.index(dataset.get_corpus_iter(), batch_size=128)

vaswani documents:   0%|          | 0/11429 [00:00<?, ?it/s]
vaswani documents:   1%|          | 128/11429 [00:00<00:55, 203.15it/s]
vaswani documents:   2%|▏         | 256/11429 [00:00<00:31, 350.35it/s]
vaswani documents:   3%|▎         | 384/11429 [00:00<00:23, 467.48it/s]
vaswani documents:   4%|▍         | 512/11429 [00:01<00:19, 558.62it/s]
vaswani documents:   6%|▌         | 640/11429 [00:01<00:22, 473.69it/s]
vaswani documents:   7%|▋         | 768/11429 [00:01<00:19, 533.95it/s]
vaswani documents:   8%|▊         | 896/11429 [00:01<00:17, 600.54it/s]
vaswani documents:   9%|▉         | 1024/11429 [00:01<00:15, 658.45it/s]
vaswani documents:  10%|█         | 1152/11429 [00:02<00:14, 702.97it/s]
vaswani documents:  11%|█         | 1280/11429 [00:02<00:16, 631.89it/s]
vaswani documents:  12%|█▏        | 1408/11429 [00:02<00:14, 677.61it/s]
vaswani documents:  13%|█▎        | 1536/11429 [00:02<00:14, 695.84it/s]
vaswani documents:  15%|█▍        | 1664/11429 [00:02<00:13, 699.62it/s]
vaswani documents:  16%|█▌        | 1792/11429 [00:03<00:14, 675.48it/s]
vaswani documents:  17%|█▋        | 1920/11429 [00:03<00:13, 682.47it/s]
vaswani documents:  18%|█▊        | 2048/11429 [00:03<00:13, 706.54it/s]
vaswani documents:  19%|█▉        | 2176/11429 [00:03<00:14, 625.20it/s]
vaswani documents:  20%|██        | 2304/11429 [00:03<00:14, 629.50it/s]
vaswani documents:  21%|██▏       | 2432/11429 [00:04<00:14, 617.53it/s]
vaswani documents:  22%|██▏       | 2560/11429 [00:04<00:13, 674.87it/s]
vaswani documents:  24%|██▎       | 2688/11429 [00:04<00:13, 671.82it/s]
vaswani documents:  25%|██▍       | 2816/11429 [00:04<00:13, 659.91it/s]
vaswani documents:  26%|██▌       | 2944/11429 [00:05<00:15, 531.14it/s]
vaswani documents:  27%|██▋       | 3072/11429 [00:05<00:15, 545.34it/s]
vaswani documents:  28%|██▊       | 3200/11429 [00:05<00:14, 568.48it/s]
vaswani documents:  29%|██▉       | 3328/11429 [00:05<00:15, 506.38it/s]
vaswani documents:  30%|███       | 3456/11429 [00:06<00:22, 362.30it/s]
vaswani documents:  31%|███▏      | 3584/11429 [00:06<00:19, 401.56it/s]
vaswani documents:  32%|███▏      | 3712/11429 [00:06<00:17, 452.31it/s]
vaswani documents:  34%|███▎      | 3840/11429 [00:06<00:15, 484.47it/s]
vaswani documents:  35%|███▍      | 3968/11429 [00:07<00:15, 481.47it/s]
vaswani documents:  36%|███▌      | 4096/11429 [00:07<00:13, 530.71it/s]
vaswani documents:  37%|███▋      | 4224/11429 [00:07<00:14, 512.29it/s]
vaswani documents:  38%|███▊      | 4352/11429 [00:08<00:14, 483.20it/s]
vaswani documents:  39%|███▉      | 4480/11429 [00:08<00:13, 512.99it/s]
vaswani documents:  40%|████      | 4608/11429 [00:08<00:12, 534.50it/s]
vaswani documents:  41%|████▏     | 4736/11429 [00:08<00:11, 559.96it/s]
vaswani documents:  43%|████▎     | 4864/11429 [00:08<00:12, 541.49it/s]
vaswani documents:  44%|████▎     | 4992/11429 [00:09<00:12, 523.62it/s]
vaswani documents:  45%|████▍     | 5120/11429 [00:09<00:12, 485.50it/s]
vaswani documents:  46%|████▌     | 5248/11429 [00:09<00:12, 508.54it/s]
vaswani documents:  47%|████▋     | 5376/11429 [00:09<00:10, 552.39it/s]
vaswani documents:  48%|████▊     | 5504/11429 [00:10<00:10, 543.37it/s]
vaswani documents:  49%|████▉     | 5632/11429 [00:10<00:11, 495.90it/s]
vaswani documents:  50%|█████     | 5760/11429 [00:10<00:11, 502.15it/s]
vaswani documents:  52%|█████▏    | 5888/11429 [00:10<00:10, 526.15it/s]
vaswani documents:  53%|█████▎    | 6016/11429 [00:11<00:10, 525.39it/s]
vaswani documents:  54%|█████▍    | 6144/11429 [00:11<00:10, 526.78it/s]
vaswani documents:  55%|█████▍    | 6272/11429 [00:11<00:09, 522.16it/s]
vaswani documents:  56%|█████▌    | 6400/11429 [00:11<00:09, 527.37it/s]
vaswani documents:  57%|█████▋    | 6528/11429 [00:12<00:10, 457.75it/s]
vaswani documents:  58%|█████▊    | 6656/11429 [00:12<00:10, 476.18it/s]
vaswani documents:  59%|█████▉    | 6784/11429 [00:12<00:10, 455.25it/s]
vaswani documents:  60%|██████    | 6912/11429 [00:13<00:10, 425.19it/s]
vaswani documents:  62%|██████▏   | 7040/11429 [00:13<00:09, 452.99it/s]
vaswani documents:  63%|██████▎   | 7168/11429 [00:13<00:09, 440.11it/s]
vaswani documents:  64%|██████▍   | 7296/11429 [00:13<00:08, 466.20it/s]
vaswani documents:  65%|██████▍   | 7424/11429 [00:14<00:07, 501.08it/s]
vaswani documents:  66%|██████▌   | 7552/11429 [00:14<00:07, 493.60it/s]
vaswani documents:  67%|██████▋   | 7680/11429 [00:14<00:07, 493.10it/s]
vaswani documents:  68%|██████▊   | 7808/11429 [00:15<00:08, 442.68it/s]
vaswani documents:  69%|██████▉   | 7936/11429 [00:15<00:07, 463.89it/s]
vaswani documents:  71%|███████   | 8064/11429 [00:15<00:06, 496.42it/s]
vaswani documents:  72%|███████▏  | 8192/11429 [00:15<00:06, 501.55it/s]
vaswani documents:  73%|███████▎  | 8320/11429 [00:15<00:05, 529.02it/s]
vaswani documents:  74%|███████▍  | 8448/11429 [00:16<00:05, 521.18it/s]
vaswani documents:  75%|███████▌  | 8576/11429 [00:16<00:05, 524.72it/s]
vaswani documents:  76%|███████▌  | 8704/11429 [00:16<00:05, 507.58it/s]
vaswani documents:  77%|███████▋  | 8832/11429 [00:16<00:04, 584.22it/s]
vaswani documents:  78%|███████▊  | 8960/11429 [00:17<00:03, 634.58it/s]
vaswani documents:  80%|███████▉  | 9088/11429 [00:17<00:03, 647.10it/s]
vaswani documents:  81%|████████  | 9216/11429 [00:17<00:03, 674.46it/s]
vaswani documents:  82%|████████▏ | 9344/11429 [00:17<00:02, 714.08it/s]
vaswani documents:  83%|████████▎ | 9472/11429 [00:17<00:02, 740.24it/s]
vaswani documents:  84%|████████▍ | 9600/11429 [00:17<00:02, 753.56it/s]
vaswani documents:  85%|████████▌ | 9728/11429 [00:18<00:02, 638.60it/s]
vaswani documents:  86%|████████▌ | 9856/11429 [00:18<00:02, 578.69it/s]
vaswani documents:  87%|████████▋ | 9984/11429 [00:18<00:02, 494.82it/s]
vaswani documents:  88%|████████▊ | 10112/11429 [00:18<00:02, 507.34it/s]
vaswani documents:  90%|████████▉ | 10240/11429 [00:19<00:02, 590.21it/s]
vaswani documents:  91%|█████████ | 10368/11429 [00:19<00:01, 629.54it/s]
vaswani documents:  92%|█████████▏| 10496/11429 [00:19<00:01, 682.06it/s]
vaswani documents:  93%|█████████▎| 10624/11429 [00:19<00:01, 727.38it/s]
vaswani documents:  94%|█████████▍| 10752/11429 [00:19<00:00, 750.16it/s]
vaswani documents:  95%|█████████▌| 10880/11429 [00:19<00:00, 783.49it/s]
vaswani documents:  96%|█████████▋| 11008/11429 [00:20<00:00, 783.58it/s]
vaswani documents:  97%|█████████▋| 11136/11429 [00:20<00:00, 790.18it/s]
vaswani documents:  99%|█████████▊| 11264/11429 [00:20<00:00, 828.75it/s]
vaswani documents: 100%|██████████| 11429/11429 [00:20<00:00, 557.96it/s]

In [1]:
import pyterrier as pt
pt.init(version='snapshot')
import pyt_splade

dataset = pt.get_dataset('irds:vaswani')
splade = pyt_splade.SpladeFactory()

indexer = pt.IterDictIndexer('./indices/craig_vaswani', pretokenised=True)

indxer_pipe = splade.indexing() >> indexer
indxer_pipe.index(dataset.get_corpus_iter())

Downloading terrier-assemblies 5.x-SNAPSHOT jar-with-dependencies to /root/.pyterrier...
Done

PyTerrier 0.10.0 has loaded Terrier 5.10-SNAPSHOT (built by jitpack on 2024-08-16 08:28) and terrier-helper 0.0.8

No etc/terrier.properties, using terrier.default.properties for bootstrap configuration.
vaswani documents: 100%|██████████| 11429/11429 [00:20<00:00, 563.49it/s]

In [5]:
splade_retr = splade.query() >> pt.BatchRetrieve('./indices/craig_vaswani', wmodel='Tf')
pt.Experiment(
    [splade_retr],
    dataset.get_topics(),
    dataset.get_qrels(),
    eval_metrics=["ndcg_cut_10", "mrt"],
    names = ["Craig SPLADE"]
)

           name  ndcg_cut_10       mrt
0  Craig SPLADE     0.002099  22.00341

In [6]:
splade_retr(dataset.get_topics().head(1))

,qid,docid,docno,rank,score,query_0,query
0,1,1680,1681,0,13.507474,measurement of dielectric constant of liquids ...,#combine:0=214.55657482147217(microwave) #comb...
1,1,4637,4638,1,13.076172,measurement of dielectric constant of liquids ...,#combine:0=214.55657482147217(microwave) #comb...
2,1,5719,5720,2,11.995042,measurement of dielectric constant of liquids ...,#combine:0=214.55657482147217(microwave) #comb...
3,1,7297,7298,3,11.894326,measurement of dielectric constant of liquids ...,#combine:0=214.55657482147217(microwave) #comb...
4,1,4107,4108,4,11.850318,measurement of dielectric constant of liquids ...,#combine:0=214.55657482147217(microwave) #comb...
...,...,...,...,...,...,...,...
995,1,3399,3400,995,3.136065,measurement of dielectric constant of liquids ...,#combine:0=214.55657482147217(microwave) #comb...
996,1,471,472,996,3.123745,measurement of dielectric constant of liquids ...,#combine:0=214.55657482147217(microwave) #comb...
997,1,2944,2945,997,3.118691,measurement of dielectric constant of liquids ...,#combine:0=214.55657482147217(microwave) #comb...
998,1,4544,4545,998,3.118523,measurement of dielectric constant of liquids ...,#combine:0=214.55657482147217(microwave) #comb...
999,1,7773,7774,999,3.117651,measurement of dielectric constant of liquids ...,#combine:0=214.55657482147217(microwave) #comb...