In [1]:
import pandas as pd

triples = pd.read_csv("/nfs/primary/SPLADE/splade_sans/data/bm25_7neg_triples.tsv", sep = "\t", header = None)
triples.columns = ["qid", "pos", "neg"]
triples

           qid       pos       neg
0            0  88000001  87256557
1            0  88000001  87256528
2            0  88000001  89148683
3            0  88000001  90329067
4            0  88000001  91184733
...        ...       ...       ...
2335545  99999  89117168  91128680
2335546  99999  89117168  90079974
2335547  99999  89117168  90025195
2335548  99999  89117168  90306895
2335549  99999  89117168  91283026

[2335550 rows x 3 columns]

In [2]:
triples[triples["pos"] == 89051339] #90359960

           qid       pos       neg
299481  138565  89051339  90359965
299482  138565  89051339  89387682
299483  138565  89051339  89051337
299484  138565  89051339  90359963
299485  138565  89051339  89051341
299486  138565  89051339  89012384
299487  138565  89051339  90359960

In [8]:
text = pd.read_csv("/nfs/primary/SPLADE/splade_sans/data/text.tsv", sep = "\t", header = None)
text.columns = ["docno", "text"]

In [10]:
text[text["docno"] == 90359960]

           docno                                               text
183345  90359960  Low back pain: comparison of chiropractic and ...

In [12]:
training_file = pd.read_pickle("/nfs/primary/sas_reranker/d2qmm_ohsumed_training_data.pkl")

In [13]:
training_file[training_file["medline_ui"] == 90359960]

,medline_ui,title,abstract,sensitivity,text,querygen,querygen_score
183382,90359960,Low back pain: comparison of chiropractic and ...,OBJECTIVE--To investigate the effects on gener...,0,Low back pain: comparison of chiropractic and ...,,[]